server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: blob:; connect-src 'self' http://resultapi:5000 https://resultapi:5000; object-src 'none'; base-uri 'self'; frame-ancestors 'self';" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
